apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'

        scrape_interval: 10s
        scrape_timeout: 5s

        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'fake-shop-app'
        static_configs:
          - targets: ['shop-app-service.default.svc.cluster.local']