apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-app
  labels:
    app: shop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-app
  template:
    metadata:
      labels:
        app: shop-app
    spec:
      containers:
      - name: shop-app
        image: nikopolides/fake-shop
        ports:
        - containerPort: 5000
        env:
        - name: PROMETHEUS_MULTIPROC_DIR
          value: "/tmp/metrics"
        - name: DB_HOST
          value: postgres-service
        - name: FLASK_APP
          value: index.py
        volumeMounts:
        - mountPath: /tmp/metrics
          name: metrics-volume
      volumes:
      - name: metrics-volume
        emptyDir: {}
