apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort # You may want LoadBalancer for external access
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana
