apiVersion: v1
kind: Service
metadata:
  name: shop-app-service
spec:
  selector:
    app: shop-app
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the service
      targetPort: 5000   # Port inside the container
      nodePort: 30001
  type: LoadBalancer     # Can be changed to LoadBalancer, NodePort or ClusterIP based on access needs
